# Generated by Django 4.2.30 on 2026-07-04 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetid', models.CharField(db_index=True, max_length=50, unique=True)),
                ('classid', models.CharField(db_index=True, max_length=50)),
                ('instanceid', models.CharField(max_length=50)),
                ('market_hash_name', models.CharField(db_index=True, max_length=255)),
                ('market_name', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('icon_url', models.CharField(blank=True, max_length=500, null=True)),
                ('icon_url_large', models.CharField(blank=True, max_length=500, null=True)),
                ('name_color', models.CharField(blank=True, max_length=10, null=True)),
                ('background_color', models.CharField(blank=True, max_length=10, null=True)),
                ('heroe', models.CharField(blank=True, default='Sin héroe', max_length=100, null=True)),
                ('rareza_tag', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_tag', models.CharField(blank=True, max_length=100, null=True)),
                ('tradable', models.BooleanField(default=False)),
                ('marketable', models.BooleanField(default=False)),
                ('commodity', models.BooleanField(default=False)),
                ('appid', models.IntegerField(default=570)),
                ('contextid', models.CharField(default='2', max_length=10)),
                ('precio_mercado', models.DecimalField(decimal_places=2, default=0, help_text='Precio actual en Steam Market (lowest_price)', max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0, help_text='Precio designado por vos para la venta', max_digits=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Item de inventario bot',
                'verbose_name_plural': 'Items de inventario bot',
                'db_table': 'inventario',
                'indexes': [models.Index(fields=['market_hash_name'], name='inventario_market__86432c_idx'), models.Index(fields=['classid', 'instanceid'], name='inventario_classid_8d35cb_idx')],
            },
        ),
    ]
