# Generated by Django 4.2.30 on 2026-07-04 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_hash_name', models.CharField(max_length=255)),
                ('icon_url', models.CharField(max_length=500)),
                ('heroe', models.CharField(blank=True, max_length=100, null=True)),
                ('rareza', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('classid', models.CharField(max_length=50)),
                ('instanceid', models.CharField(max_length=50)),
                ('assetid', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('pendiente_envio', 'Pendiente de envío al bot'), ('en_bot', 'En poder del bot'), ('vendido', 'Vendido'), ('cancelado', 'Cancelado')], default='pendiente_envio', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='usuario.usuario')),
            ],
        ),
    ]
